feat: NestJS REST starter kit
juliandavidmr/awesome-nestjs pull request #142
Opened 2021-06-01 10:48 UTC by yashmurty

## Resource type _(required)_

- [x] GitHub Repository:
    - [x] **(Required)** I confirm that the GitHub repository has more than **10 stars**.
    - [x] **(Required)** The repository is not archived.
- [ ] Video.
- [ ] Tutorial.
- [ ] Meetups.
- [ ] Improve documentation _(grammatical corrections, improve doc style, ...)_.

> If your contribution is NOT a GitHub repository, then you can skip the next titles, except "Rules".

## Description _(required)_

A production-ready NestJS boilerplate by MonstarLab. Core features: JWT Authentication, RBAC Authorization, TypeORM, winston logger, Pagination, Docker Ready, Auto-generated Swagger. Minor features: prettier, commit-linting husky hooks, SonarCloud github actions, docker-compose.

## Link _(required)_

https://github.com/monstar-lab-oss/nestjs-starter-rest-api

## Rules _(required)_

- [x] **NestJS / Nest**: It's not nest, nestjs, nest.js, and other variants.
- [x] **Node.js**: It's not nodejs, node, and other variants.

2021-06-02 22:56 UTC, juliandavidmr requested changes
Hey @yashmurty, can you shorten the description to a maximum of two lines?, Or max 22 words.

2021-06-04 09:29 UTC, yashmurty commented
@juliandavidmr 
Thank you for the review. 
Can you PTAL again? 🙇

2021-06-04 14:14 UTC, juliandavidmr approved these changes

2021-06-04 14:14 UTC, juliandavidmr commented
@yashmurty, thanks for your contribution.

2021-06-04 14:14 UTC, merged